/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-10 11:49:51
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

const int MAX_N = 2 * 1e5 + 10;
typedef long long ll;
ll arr[MAX_N];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  //cout << T << "\n";

  for (int t = 0; t < T; ++t)
  {
    int n;
    ll S = 0;
    cin >> n;
    map<ll, vector<ll>> mp;

    for (int i = 0; i < n + 2; ++i)
    {
      cin >> arr[i];
      S += arr[i];
      mp[arr[i]].push_back(i);
    }
    //cout << S << "\n";
    bool solved = false;
    for (int i = 0; i < n + 2; ++i)
    {
      if (solved)
        break;
      ll left = S - arr[i];
      ll half = left / 2;
      if (left % 2 == 0 && mp.count(half) != 0)
      {
        //cout << i << "\n";
        vector<ll> pos = mp[half];
        for (auto k : pos)
        {
          if (k != i)
          {
            for (int j = 0; j < n + 2; ++j)
            {
              if (j != i && j != k)
              {
                cout << arr[j] << " ";
              }
            }
            cout << "\n";
            solved = true;
            break;
          }
        }
      }
    }
    if (!solved)
    {
      cout << -1 << "\n";
    }
  }

  return 0;
}
