/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-18 20:02:13
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int pos[51];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int N, Q;
  cin >> N >> Q;
  int tmp;
  for (int i = 1; i <= N; ++i) {
    cin >> tmp;
    if (pos[tmp] == 0) {
      pos[tmp] = i;
    }
  }
  for (int q = 0; q < Q; ++q) {
    cin >> tmp;
    int p = pos[tmp];
    cout << p << " ";
    for (int i = 1; i <= 50; ++i) {
      if (i == tmp) continue;
      if (pos[i] == 0) continue;
      if (pos[i] < p) pos[i]++;
    }
    pos[tmp] = 1;
  }

  return 0;
}
