/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-22 21:24:19
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

const int N_MAX = 2010;
int arr[N_MAX];
int pre[N_MAX];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--) {
    int N;
    cin >> N;
    for (int i = 1; i <= N; ++i) {
      cin >> arr[i];
      pre[i] = arr[i] ^ pre[i - 1];
    }
    bool ok = pre[N] == 0;
    for (int i = 1; i <= N; ++i) {
      for (int j = i + 1; j <= N; ++j) {
        ok |= (pre[i] == (pre[j] ^ pre[i])) && (pre[i] == (pre[N] ^ pre[j]));
      }
    }
    if (ok) {
      cout << "YES\n";
    }
    else {
      cout << "NO\n";
    }
  }
  return 0;
}
