/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-05-01 08:10:08
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

deque<char> str;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  string s;
  cin >> s;
  int n = s.size();
  bool right = true;
  for (int i = 0; i < n; ++i) {
    if (s[i] == 'R') {
      right = !right;
      continue;
    }
    if (right) {
      if (str.size()) {
        if (str.back() == s[i]) {
          str.pop_back();
        }
        else {
          str.push_back(s[i]);
        }
      }
      else {
        str.push_back(s[i]);
      }
    }
    else {
      if (str.size()) {
        if (str.front() == s[i]) {
          str.pop_front();
        }
        else {
          str.push_front(s[i]);
        }
      }
      else {
        str.push_front(s[i]);
      }
    }
  }
  if (right) {
    auto it = str.begin();
    for (;it != str.end(); ++it) {
      cout << *it;
    }
  }
  else {
    auto it = str.rbegin();
    for (;it != str.rend(); ++it) {
      cout << *it;
    }
  }
  return 0;
}
