/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-30 09:14:10
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--) {
    int N;
    string s;
    cin >> N >> s;
    int good = 0;
    int bad = 0;
    bool ok = false;
    for (int i = 0; i < N; ++i) {
      if (s[i] == '1') {
        good++;
      }
      else {
        bad++;
      }
      if (good >= bad) {
        ok = true;
        break;
      }
    }
    if (ok) {
      cout << "YES\n";
    }
    else {
      cout << "NO\n";
    }
  }
  return 0;
}
