/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-18 20:02:13
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int length(ll x) {
  int ret = 0;
  while (x) {
    x /= 10;
    ret++;
  }
  return ret;
}

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--) {
    int A, B, C;
    cin >> A >> B >> C;
    int g = 1;
    for (int i = 1; i < C; ++i) {
      g *= 2;
      g *= 5;
    }
    ll x = g, y = g;
    while (length(x) < A) {
      x *= 2;
    }
    while (length(y) < B) {
      y *= 5;
    }
    cout << x << " " << y << "\n";
  }
  return 0;
}
