/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-16 09:35:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--)
  {
    int N, TMP;
    cin >> N;
    vector<int> par, impar;
    for (int i = 0; i < N; ++i)
    {
      cin >> TMP;
      if (TMP & 1)
      {
        impar.push_back(TMP);
      }
      else
      {
        par.push_back(TMP);
      }
    }
    for (auto x : par)
    {
      cout << x << " ";
    }
    for (auto x : impar)
    {
      cout << x << " ";
    }
    cout << "\n";
  }
  return 0;
}
