/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-23 09:35:01
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

const int MAX_N = 510;
int MAT[MAX_N][MAX_N];

bool valid(int x, int y) {
  return 0 <= x && 0 <= y;
}

bool occupied(int x, int y) {
  return MAT[x][y] != 0;
}

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int N, x, y;
  cin >> N;
  for (int i = 0; i < N; ++i) {
    int X;
    cin >> X;
    x = y = i;
    MAT[x][y] = X;
    for (int k = 0; k < X - 1; ++k) {
      if (valid(x, y - 1) && !occupied(x, y - 1)) {
        y--;
        MAT[x][y] = X;
      }
      else {
        x++;
        MAT[x][y] = X;
      }
    }
  }
  for (int i = 0; i < N; ++i) {
    for (int j = 0; j <= i; ++j) {
      cout << MAT[i][j] << " ";
    }
    cout << "\n";
  }


  return 0;
}
