/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-05-08 07:06:37
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

const int MAX_N = 2 * 1e5 + 100;
int arr[MAX_N];
int cnt[210];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int N, V;
  cin >> N;
  ll ans = 0;
  for (int i = 0; i < N; ++i) {
    cin >> V;
    ans += cnt[V % 200];
    cnt[V % 200] += 1;
  }

  cout << ans;


  return 0;
}
