/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-18 20:02:13
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int state[26];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int N, K;
  cin >> N >> K;
  state[K - 1] = 1;
  int cur = 0;
  string s = "";
  for (int i = 0; i < N; ++i) {
    if (K == 1) {
      s += 'a';
      continue;
    }
    s += (cur + 'a');
    int ne = state[cur];
    state[cur] = (state[cur] + 1) % K;
    cur = ne;
  }
  cout << s << "\n";

  return 0;
}
