/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-10 13:50:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--)
  {
    string A, B;
    cin >> A >> B;

    if (A.size() > B.size())
    {
      swap(A, B);
    }

    int n = A.size(), m = B.size();
    int ans = n + m;

    for (int i = 0; i < n; ++i)
    {
      for (int j = i; j < n; ++j)
      {
        int len = j - i + 1;
        for (int k = 0; k <= m - len; ++k)
        {
          bool eq = true;
          for (int x = 0; x < len; ++x)
          {
            if (A[i + x] != B[k + x])
              eq = false;
          }
          if (eq)
          {
            int cur = n + m - 2 * len;
            ans = min(ans, cur);
          }
        }
      }
    }
    cout << ans << "\n";
  }
  return 0;
}
