/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-30 09:06:40
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  string key = "EQUINOX", s;
  while (T--) {
    int N, A, B;
    cin >> N >> A >> B;
    ll sarthrak = 0;
    ll anuradha = 0;
    for (int i = 0; i < N; ++i) {
      cin >> s;
      bool sar = false;
      for (int j = 0; j < key.size(); ++j) {
        if (s[0] == key[j]) {
          sarthrak += A;
          sar = true;
          break;
        }
      }
      if (!sar) {
        anuradha += B;
      }
    }
    if (sarthrak == anuradha) {
      cout << "DRAW\n";
    }
    else if (sarthrak > anuradha) {
      cout << "SARTHAK\n";
    }
    else {
      cout << "ANURADHA\n";
    }
  }
  return 0;
}
