/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-10 13:50:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

const int N_MAX = 2 * 1e5 + 10;
int arr[N_MAX];
int least[N_MAX];
int most[N_MAX];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--)
  {
    int N;
    cin >> N;
    for (int i = 0; i < N; ++i)
    {
      cin >> arr[i];
      least[i] = most[i] = 0;
    }

    set<int> left;
    for (int i = 1; i <= N; ++i)
    {
      left.insert(i);
    }

    int last = arr[0];
    least[0] = most[0] = arr[0];
    left.erase(last);

    for (int i = 1; i < N; ++i)
    {
      if (arr[i] != last)
      {
        least[i] = most[i] = arr[i];
        //cout << arr[i] << "@\n";
        left.erase(arr[i]);
      }
      last = arr[i];
    }
    auto it = left.begin();
    for (int i = 0; i < N; ++i)
    {
      if (least[i] == 0)
      {
        least[i] = *it;
        it++;
      }
      cout << least[i] << " ";
    }
    cout << "\n";
    for (int i = 0; i < N; ++i)
    {
      if (most[i] != 0)
      {
        last = most[i];
      }
      else
      {
        auto it = left.lower_bound(last);
        it--;
        most[i] = *it;
        left.erase(it);
      }
      cout << most[i] << " ";
    }
    cout << "\n";
  }
  return 0;
}
