/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-10 13:50:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--)
  {
    int n, k;
    string s;
    cin >> n >> k >> s;
    int first = 0;
    for (int i = 0; i < n; ++i)
    {
      if (s[i] == '*')
      {
        first = i;
        break;
      }
    }

    int ans = 1;
    int i = first;
    while (i < n)
    {
      int j = min(i + k, n - 1);
      bool found = false;
      for (; j > i; --j)
      {
        if (s[j] == '*')
        {
          i = j;
          found = true;
          ans++;
          break;
        }
      }
      if (!found)
        break;
    }

    cout << ans << "\n";
  }
  return 0;
}
