/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-05-07 09:35:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--) {
    ll A, B;
    cin >> A >> B;
    if (B == 1) {
      cout << "NO\n";
      continue;
    }
    if (B == 2) {
      B *= 2;
    }
    ll x = A;
    ll y = A * (B - 1);
    ll z = x + y;
    cout << "YES\n";
    cout << x << " " << y << " " << z << "\n";
  }
  return 0;
}
