/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-23 08:33:08
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int P, Q, L, R, a, b, c, d;
  cin >> P >> Q >> L >> R;
  vector<pii> Z_sched, X_sched;
  for (int i = 0; i < P; ++i) {
    cin >> a >> b;
    Z_sched.push_back({ a, b });
  }
  for (int i = 0; i < Q; ++i) {
    cin >> c >> d;
    X_sched.push_back({ c, d });
  }
  int ans = 0;
  for (int i = L; i <= R; ++i) {
    bool yes = false;
    for (auto& [a, b] : X_sched) {
      for (auto& [c, d] : Z_sched) {
        yes |= (max(a + i, c) <= min(b + i, d));
      }
    }
    if (yes) {
      ans++;
    }
  }
  cout << ans;
  return 0;
}
