/* Generated by powerul Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-19 08:35:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;
const int MOD = 1e9 + 7;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--) {
    int N, K;
    cin >> N >> K;
    ll ans = 1;

    for (int i = 0; i < K; ++i) {
      ans = (ans * N) % MOD;
    }

    cout << ans << "\n";
  }
  return 0;
}
