/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-10 13:50:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int t;
  cin >> t;
  while (t--)
  {
    ll n, m, x;
    cin >> n >> m >> x;
    ll row = (x - 1) % n;
    ll col = (x - 1) / n;
    //cout << row << " " << col << "\n";
    ll ans = row * m + col + 1;
    cout << ans << "\n";
  }
  return 0;
}
