/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-23 07:22:10
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;
const int MAX_N = 1e5 + 100;
int arr[MAX_N], dp[MAX_N];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--) {
    int N;
    cin >> N;
    for (int i = 1; i <= N; ++i) {
      cin >> arr[i];
      dp[i] = 1;
    }
    int ans = 0;
    for (int i = 1; i <= N; ++i) {
      for (int j = i * 2; j <= N; j += i) {
        if (arr[j] > arr[i]) {
          dp[j] = max(dp[j], dp[i] + 1);
        }
      }
      ans = max(ans, dp[i]);
    }
    cout << ans << "\n";
  }
  return 0;
}
