/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-16 09:35:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;
  while (T--)
  {
    int N;
    string s;
    cin >> N >> s;
    stack<int> ts;
    stack<int> ms;
    for (int i = N - 1; i >= 0; --i)
    {
      if (s[i] == 'T')
      {
        ts.push(i);
      }
      else
      {
        ms.push(i);
      }
    }
    int cnt = N / 3;
    bool ok = (ts.size() == cnt * 2) && (ms.size() == cnt);
    vector<int> tms;
    if (ok)
    {
      for (int i = 0; i < cnt; ++i)
      {
        int a = ts.top();
        ts.pop();
        int b = ms.top();
        ms.pop();
        if (a < b)
        {
          tms.push_back(b);
        }
        else
        {
          ok = false;
        }
      }
    }
    if (ok && tms.size() == cnt)
    {
      for (auto a : tms)
      {
        int b = ts.top();
        ts.pop();
        if (a > b)
        {
          ok = false;
        }
      }
    }
    if (ok)
    {
      cout << "YES\n";
    }
    else
    {
      cout << "NO\n";
    }
  }
  return 0;
}
