/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-30 09:24:23
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

const int MAX_N = 1e5 + 10;
const ll MOD = 1e9 + 7;
ll arr[MAX_N];

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int N, Q;
  cin >> N;
  ll S = 0;
  for (int i = 0; i < N; ++i) {
    cin >> arr[i];
    arr[i] = (arr[i] + MOD) % MOD;
    S += arr[i];
  }
  cin >> Q;
  for (int i = 1; i <= Q; ++i) {
    S = (S + S) % MOD;
    cout << S << "\n";
  }

  return 0;
}
