/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-16 09:35:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

int main() {
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  int T;
  cin >> T;

  while (T--) {
    int N;
    cin >> N;
    string S[3];
    for (int i = 0; i < 3; ++i) {
      cin >> S[i];
    }
    int p[3];
    p[0] = p[1] = p[2] = 0;
    string ans = "";
    bool done = false;
    int completed = 0;
    while (!done) {
      int zero = 0;
      for (int i = 0; i < 3; ++i) {
        if (S[i][p[i]] == '0') zero++;
      }
      char add;
      if (zero >= 2) {
        add = '0';
      }
      else {
        add = '1';
      }
      ans += add;

      for (int i = 0; i < 3; ++i) {
        if (S[i][p[i]] == add) p[i]++;
      }
      for (int i = 0; i < 3; ++i) {
        if (p[i] == 2 * N) {
          completed = i;
          done = true;
        }
      }
    }
    int id = 0, cnt = 0;
    for (int i = 0; i < 3; ++i) {
      if (i == completed) continue;
      if (p[i] > cnt) {
        id = i;
        cnt = p[i];
      }
    }
    while (p[id] < 2 * N) {
      ans += S[id][p[id]];
      p[id]++;
    }
    cout << ans << "\n";
  }

  return 0;
}
