/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-05-30 07:07:36
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;
typedef pair<ll, ll> pll;

int main()
{
  cin.tie(0), cout.sync_with_stdio(0);
  ll N, K;
  cin >> N >> K;
  vector<pll> friends(N);
  ll A, B;
  for (int i = 0; i < N; ++i) {
    cin >> A >> B;
    friends[i] = { A, B };
  }
  sort(friends.begin(), friends.end());
  ll cur = K;
  for (auto& [a, b] : friends) {
    if (a <= cur) {
      cur += b;
    }
    else {
      break;
    }
  }
  cout << cur;

  return 0;
}
