/* Generated by powerful Codeforces Tool
 * You can download the binary file in here https://github.com/xalanq/cf-tool (Windows, macOS, Linux)
 * Author: mia_ortizma
 * Time: 2021-04-19 08:35:02
**/

#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;

const int N_MAX = 1e5 + 100;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);

  int N;
  cin >> N;

  vector<int> res;
  ll prod = 1;

  for (int i = 1; i < N; ++i) {
    if (__gcd(i, N) == 1) {
      prod = (prod * i) % N;
      res.push_back(i);
    }
  }
  int sz = res.size();
  if (prod != 1) sz--;
  cout << sz << "\n";
  for (auto x : res) {
    if (x != 1 && prod == x) {
      continue;
    }
    cout << x << " ";
  }

  return 0;
}
